export const IPC_CHANNELS = {
  SYSTEM_PING: 'SYSTEM_PING',
  GET_SYSTEM_INFO: 'GET_SYSTEM_INFO',
  EXECUTE_AGENT_TASK: 'EXECUTE_AGENT_TASK',
  FETCH_USER_PROFILE: 'FETCH_USER_PROFILE',
  UPDATE_USER_SETTINGS: 'UPDATE_USER_SETTINGS',
} as const;

export const DEFAULT_API_PORT = 4000;
export const DEFAULT_API_HOST = 'localhost';
